config/routes.rb
Rails.application.routes.draw do
  root "todos#index"

  post "/todos", to: "todos#create", as: "todos"
  get "todos/:id", to: "todos#show", as: "todo"
  patch "todos/:id", to: "todos#update"
  put "todos/:id", to: "todos#update"
  delete "/todos/:id", to: "todos#destroy"
  get "/todos/:id/edit", to: "todos#edit", as: "edit_todo"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  def index
    @todo = Todo.new
    @todos = Todo.order(created_at: :desc)
  end

  def show
    respond
  end

  def create
    @todo = Todo.new(todo_params)
    @count = Todo.count + 1

    respond if @todo.save
  end

  def edit
    respond if @todo.present?
  end

  def update
    respond if @todo.update(todo_params)
  end

  def destroy
    @todo.destroy
    @count = Todo.count

    respond
  end

  private
  def todo_params
    params.require(:todo).permit(:title)
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def respond
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper

  def edit_button id
    button_to :edit, edit_todo_path(id), method: :get, data: { turbo_stream: true }
  end

  def delete_button id
    button_to :delete, todo_path(id), method: :delete
  end

  def cancel_button id
    button_to :cancel, todo_path(id), method: :get, data: { "turbo_stream": true }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo.html.erb
<li id="todo_<%= todo.id %>">
  <span>
    <%# <input type="checkbox"> %>
    <%= todo.title %>
  </span>
  <span>
    <%= edit_button(todo.id) %>
    <%= delete_button(todo.id) %>
  </span>
</li>

app/views/todos/_todo.turbo_stream.erb
<li id="todo_<%= todo.id %>">
  <span>
    <%# <input type="checkbox"> %>
    <%= todo.title %>
  </span>
  <span>
    <%= edit_button(todo.id) %>
    <%= delete_button(todo.id) %>
  </span>
</li>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.prepend "todos" do %>
  <%= render "todo", todo: @todo %>
<% end %>

<%= turbo_stream.replace "todos_count" do %>
  <h2 id="todos_count"><%= pluralize(@count, "todo") %> left</h2>
<% end %>

app/views/todos/destroy.turbo_stream.erb
<%= turbo_stream.remove "todo_#{@todo.id}" %>

<%= turbo_stream.replace "todos_count" do %>
  <h2 id="todos_count"><%= pluralize(@count, "todo") %> left</h2>
<% end %>

app/views/todos/edit.turbo_stream.erb
<%= turbo_stream.replace "todo_#{@todo.id}" do %>
  <li id="todo_<%= @todo.id %>">
    <span>
      <%= form_with model: @todo, url: todo_path(@todo.id) do |f| %>
        <%= f.text_field :title, value: @todo.title %>
        <%= f.submit "Save" %>
      <% end %>
    </span>
    <span>
      <%= cancel_button(@todo.id) %>
    </span>
  </li>
<% end %>

app/views/todos/index.html.erb
<h1>Todo or not Todo</h1>

<h2 id="todos_count"><%= pluralize(@todos.length, "todo") %> left</h2>

<%= form_with model: @todo, url: todos_path do |f| %>
  <%= f.text_field :title, placeholder: "add new todo", value: nil, required: true %>
  <%= f.submit "Add", html: { onclick: "clearInput" } %>
<% end %>

<ul id="todos">
  <% @todos.each do |todo| %>
    <%= render "todo", todo: todo %>
  <% end %>
</ul>

app/views/todos/show.turbo_stream.erb
<%= turbo_stream.replace "todo_#{@todo.id}" do %>
  <%= render "todo", todo: @todo %>
<% end %>

app/views/todos/update.turbo_stream.erb
<%= turbo_stream.replace "todo_#{@todo.id}" do %>
  <%= render "todo", todo: @todo %>
<% end %>